import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body > <AntdRegistry>{children}</AntdRegistry></body>
    </html>
  );
}
